services:
  - type: web
    name: express-mongo-auth
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: MONGO_URI
        fromEnvironment: MONGO_URI
